[package]
name = "carina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1"
clap = "3.2"
log = "0.4.0"
env_logger = "0.8.4"
rayon = "1.5"
serde = { version="1.0", features = ["derive"] }
serde_json = "1.0"
indicatif = {version = "0.16", features = ["rayon"]}