[package]
name = "sage-cloudpath"
version = "0.10.0"
authors = ["Michael Lazear <michaellazear92@gmail.com"]
edition = "2021"
rust-version = "1.62"
description = "A very fast proteomics database search tool"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-compression = { version = "0.3", features = ["tokio", "gzip"] }
aws-config = "0.54.1"
aws-sdk-s3 = "0.24"
bytes = "1.0"
http = "0.2"
futures = "0.3"
once_cell = "1.0"
tokio = { version = "1.0", features = ["fs", "io-util", "rt"] }